---
title: "Dropout check"
author: "Nicholas Coles"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---
Prepare environment
```{r}
## --------------------------------------------------------------------------------------
# clear environment
rm(list = ls())

# install (if necessary) and load packages
  # function written by stevenworthington 
  Ipak <- function(pkg){
      new.pkg <- pkg[!(pkg %in% installed.packages()[, 'Package'])]
      
      if (length(new.pkg)) 
          install.packages(new.pkg, dependencies = TRUE)
      
      sapply(pkg, require, character.only = TRUE)
  }

  # vector of necessary packages
  packages <- c('tidyverse', 'ggplot2', 
                'qualtRics', 'googlesheets4')
  
  # using vector of packages, call ipak function
  Ipak(packages)
  
  # delete vestigial
  rm(packages, Ipak)


## --------------------------------------------------------------------------------------
# Dangs API credential at UCSD
qualtrics_api_credentials(
  api_key = 'urh7PtWEEOkAzrbjmYQC2FoipCvCT4n8ZIByL5rH', 
  base_url = 'iad1.qualtrics.com',
  install = TRUE,
  overwrite = TRUE)

readRenviron("~/.Renviron")

## --------------------------------------------------------------------------------------
# fetch survey
DF <- fetch_survey(surveyID = 'SV_1YQ3FmlbEHp1RIO',
                   force_request = T,
                   label = F,
                   convert = F)
```

For each lab, remove previews, filter out non-consenters, and create stem-and-leaf plot showing how far their participants are getting through the study
```{r}
for(l in c("POL_01", "DNK_01", "MYS_01")){
  d <- DF %>% 
    filter(lab == l,
           DistributionChannel != "preview",
           consent == 1)
  
  print(l)
  stem(d$Progress)
}
```

