---
title: "GlobalGratitude_Maps"
author: "Annabel Dang"
date: "2024-11-15"
output: html_document
---

```{r libraries}
library(dplyr)
library(effsize)
library(ggplot2)
library(qualtRics)
library(metafor)
library(scales)
library(ggtext)
library(sf)
library(RColorBrewer)
library(rnaturalearth)

```
```{r survey data}
# fetch survey
DF <- fetch_survey(surveyID = 'SV_1YQ3FmlbEHp1RIO',
                   force_request = T,
                   label = F,
                   convert = F)

# fix known issues
data <- DF %>% 
  
  # 4/22/2024 TUR_01 used real link for testing purposes
  filter(ResponseId != "R_42KUGZSS76NgWH7",
         ResponseId != "R_4W4EXfgeyk1rCYF",
         ResponseId != "R_45Z862EIfzYcin4",
         ResponseId != "R_7BhJx9Ci7THupmF",
         ResponseId != "R_42Lv9fg5qi9V9xm",
         ResponseId != "R_2kFa26mh78uevnz",
         ResponseId != "R_4DRThnH8LgbEvM8",
         ResponseId != "R_4r1kAEqQCo1PNn6",
         ResponseId != "R_4GQErqyYDlRWVwZ",
         ResponseId != "R_4SGF0GCHSHIN0ls",
         ResponseId != "R_6Pndj5c7sr1pcU3",
         ResponseId != "R_8lQxsY2ITg7HKh1",
         #USA_01 duplicate data
         ResponseId != "R_6rDfD5u84z6WufT",
         DistributionChannel != "preview",
         consent == 1,
         Progress > 95,
         condition_type != "NA",
         lab != "NA")

```
```{r set up}
data <- data %>%
  select(StartDate:ls_5, sex:totalOnTask)

data$gratitude_all <- rowMeans(data[, c("grateful", "thankful", "appreciative")], na.rm = TRUE)
data$happy_all <- rowMeans(data[, c("happy", "satisfied", "content", "joyful", "pleased")], na.rm = TRUE)
data$optimistic_all <- rowMeans(data[, c("optimistic", "hopeful")], na.rm = TRUE)
data$sad_all <- rowMeans(data[, c("sad", "depressed", "anxious", "nervous")], na.rm = TRUE)
data$indebted_all <- rowMeans(data[, c("indebted", "obligated")], na.rm = TRUE)
data$envy_all <- rowMeans(data[, c("envious", "bitter", "jealous")], na.rm = TRUE)
data$ls_all <- rowMeans(data[, c("ls_1", "ls_2", "ls_3", "ls_4", "ls_5")], na.rm = TRUE)

data$condition_type <- factor(data$condition_type, levels = c("control", "intervention"))
data$condition_type <- relevel(data$condition_type, ref = "intervention")

```
```{r set up country names}

data <- data %>%
  mutate(country = case_when(
    lab == "POL_01" ~ "Poland",
    lab == "DNK_01" ~ "Denmark",
    lab == "TUR_01" ~ "Turkey",
    lab == "MYS_01" ~ "Malaysia",
    lab == "USA_01" ~ "United States of America",
    lab == "USA_02" ~ "United States of America",
    lab == "NGA_01" ~ "Nigeria",
    lab == "NGA_02" ~ "Nigeria",
    lab == "CAN_01" ~ "Canada",
    lab == "FRA_01" ~ "France",
    lab == "AUS_01" ~ "Australia",
    lab == "CHL_01" ~ "Chile",
    lab == "DEU_01" ~ "Germany",
    lab == "GRC_01" ~ "Greece",
    lab == "HUN_01" ~ "Hungary",
    lab == "ISR_01" ~ "Israel",
    lab == "IRL_01" ~ "Ireland",
    lab == "MEX_01" ~ "Mexico",
    lab == "ITA_01" ~ "Italy",
    lab == "PRT_01" ~ "Portugal",
    lab == "BRA_01" ~ "Brazil",
    lab == "NLD_01" ~ "Netherlands",
    lab == "GBR_01" ~ "United Kingdom",
    lab == "ESP_01" ~ "Spain",
    lab == "ZAF_01" ~ "South Africa",
    lab == "KOR_01" ~ "South Korea",
    lab == "SWE_01" ~ "Sweden",
    lab == "IND_01" ~ "India",
    lab == "COL_01" ~ "Colombia",
    lab == "CHN_01" ~ "China",
    lab == "KAZ_01" ~ "Kazakhstan",
    lab == "NOR_01" ~ "Norway",
    lab == "JPN_01" ~ "Japan",
    lab == "GHA_01" ~ "Ghana",
    lab == "THA_01" ~ "Thailand",
    TRUE ~ NA_character_
  ))

control_data <- subset(data, condition_type == "control")
intervention_data <- subset(data, condition_type == "intervention")

unique_labs <- unique(data$country)
condition_names <- c("list", "letter", "text", "hk.list", "sub", "god.letter")

```


```{r gratitude}

grat_results_df <- data.frame(
  country = character(),
  overall_eff_size = numeric(),
  stringsAsFactors = FALSE
)

gratitude_results_list <- sapply(unique_labs, function(lab_name){
  
  # Subset data for the current lab
  lab_data <- subset(data, country == lab_name)
  
  # Count observations for each condition type
  condition_counts <- table(lab_data$condition_type)

    # Check if both groups doesn't have at least 20 observations
  if (any(condition_counts < 20)) {
    return(NULL)  # Skip if the condition is not met
  }

  # Calculate Cohen's d effect size
  effect_size_result <- cohen.d(gratitude_all ~ condition_type, data = lab_data)
  
  # Store the results in the data frame
  result <- data.frame(
    country = lab_name,
    overall_eff_size = effect_size_result$estimate,
    stringsAsFactors = FALSE
  )
  
  # Return the result for the current lab
  return(result)
}, simplify = FALSE)

grat_results_df <- do.call(rbind, gratitude_results_list)

print(grat_results_df)


```
```{r gratitude map}
world_sf <- ne_download(scale = 110, type = "countries", category = "cultural", returnclass = "sf")

world_data <- world_sf %>%
  left_join(grat_results_df, by = c("NAME" = "country"))

# Plot the map with effect sizes
ggplot(world_data) +
  geom_sf(aes(fill = overall_eff_size), color = "white", size = 0.2) +  # Apply color to the map fill
  scale_fill_gradient(low = "blue", high = "red", name = "Effect Size", na.value = "gray90") +  # Color scale from blue (low) to red (high)
  labs(title = "World Map of Overall Gratitude Effect Sizes") +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(hjust = 0.5)
  )

```

