---
title: "Figure 1: Cross-cultural Visualization"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Visualizes cross-cultural data, generating Figure 1 for the manuscript"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
# Install packages
source("setup.R")
```

# Open cross-cultural values
```{r}
# Fetch cross-cultural data
DF <-
  read.csv(here(
    "data/final-data",
    "crossculturalmod.csv"
  ))

# Standardize variables
DF <-
  DF %>%
  mutate(
    dist.us =
      if_else(country == "United States" &
        is.na(dist.us),
      0,
      dist.us
      )
  ) %>%
  mutate_at(
    .vars =
      vars(
        dist.us,
        relational_mobility:indulgence
      ),
    ~ scales::rescale(., to = c(-1, 1))
  )
```

# Create figure 1a (cultural distance)
```{r}
# Create figure 1a
fig.1a <-
  ggplot(
    data = DF,
    aes(
      x = dist.us,
      y = .2
    )
  ) +

  # population density (all countries)
  geom_density(
    data = DF,
    aes(
      x = dist.us,
      y = ..scaled..
    ),
    color = "grey80",
    alpha = 0.5
  ) +

  # sample density (sampled countries)
  geom_density(
    data = DF %>%
      filter(sample == "yes"),
    aes(
      x = dist.us,
      y = ..scaled..
    ),
    color = "#3C5488",
    alpha = 0.5
  ) +

  # rug lines: unsampled countries
  geom_linerange(
    data = DF %>% filter(sample == "no"),
    aes(ymin = 0, ymax = 0.1),
    color = "grey35"
  ) +

  # rug lines: sampled countries
  geom_linerange(
    data = DF %>% filter(sample == "yes"),
    aes(
      ymin = 0, ymax = 0.2,
      color = country
    )
  ) +

  # country labels
  geom_text_repel(
    data = DF %>% filter(sample == "yes"),
    aes(
      label = country,
      color = country,
      y = 1
    ),
    direction = "y",
    nudge_y = -0.5,
    force = 2,
    max.overlaps = Inf,
    segment.color = NA,
    size = 3
  ) +
  # theme
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title.y = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line.y = element_blank(),
    strip.background = element_blank()
  ) +
  xlab("Cultural Distance (From the United States)") +

  # Grey line for "All countries"
  geom_segment(
    aes(
      x = .6, xend = .75,
      y = .8, yend = .8
    ),
    color = "grey80",
    size = 1,
    inherit.aes = FALSE
  ) +
  geom_text(
    aes(
      x = .77,
      y = .8,
      label = "All Countries"
    ),
    color = "grey50",
    hjust = 0,
    size = 3,
    inherit.aes = FALSE
  ) +

  # Blue line for "Sampled countries"
  geom_segment(
    aes(
      x = .6, xend = .75,
      y = .7, yend = .7
    ),
    size = 1,
    color = "#3C5488",
    inherit.aes = FALSE
  ) +
  geom_text(
    aes(
      x = .77, y = .7,
      label = "Sampled Countries"
    ),
    color = "grey50",
    hjust = 0,
    size = 3,
    inherit.aes = FALSE
  )

fig.1a
```

# Map facet
```{r}
# Download world data
world <- ne_countries(
  scale = "medium",
  returnclass = "sf"
)

# Fix missing ISO values in world data
world[world$name == "France", ]$iso_a3 <- "FRA"
world[world$name == "Norway", ]$iso_a3 <- "NOR"
```

#Create figure 1b
```{r}
# Filter sampled countries
sampled_iso <- DF %>%
  filter(sample == "yes") %>%
  pull(iso)

# Get world map
world <- ne_countries(
  scale = "medium",
  returnclass = "sf"
)

# Create fig.1b
fig.1b <- ggplot() +
  # Base world map (all countries, no fill)
  layer_spatial(
    data = world,
    color = NA
  ) +

  # Highlight sampled countries
  layer_spatial(
    data = world %>% filter(iso_a3 %in% sampled_iso),
    aes(fill = iso_a3)
  ) +

  # Use equal-area projection
  coord_sf(crs = "ESRI:54030") +

  # Minimal theme, remove legend and axes
  theme_void() + # removes axes, gridlines, and background
  theme(legend.position = "none")
```

# Create figure 1c (cross-cultural moderators)
```{r}
# Rename columns
fig1.DF <-
  DF %>%
  pivot_longer(relational_mobility:indulgence) %>%
  mutate(
    name =
      fct_recode(name,
        "Relational Mobility" = "relational_mobility",
        "Responsibilism" = "responsibilism",
        "Tightness" = "tightness",
        "Religiosity" = "relig_mean",
        "GDP" = "mean_GDP",
        "Residential Mobility" = "resmobility",
        "Power Distance" = "power.distance",
        "Individualism" = "individualism",
        "Motivation" = "motivation",
        "Uncertainty Avoidance" = "uncertainty.avoidance",
        "Long Term Orientation" = "long.term.orientation",
        "Indulgence" = "indulgence"
      )
  )
```

Calculate percentage overlap
```{r}
per.overlap <-
  sapply(unique(fig1.DF$name),
    simplify = F,
    USE.NAMES = T,
    function(x) {
      # filter by outcome and include all countries
      d.pop <-
        fig1.DF %>%
        filter(
          name == x,
          !is.na(value)
        )

      # pull out only sampled countries
      d.sample <- d.pop %>%
        filter(sample == "yes")

      # calculate overlap
      o <-
        overlap(
          x = list(
            d.pop$value,
            d.sample$value
          ),
          type = "1"
        )

      cbind(
        x = as.character(x),
        overlap =
          round(
            o$OV * 100,
            2
          ) %>%
            as.numeric()
      ) %>%
        as.data.frame() %>%
        return()
    }
  ) %>%
  bind_rows() %>%
  mutate(
    overlap =
      as.numeric(overlap)
  )
```

Inspect percent overlap
```{r}
mean(per.overlap$overlap,
  na.rm = T
)

sd(per.overlap$overlap,
  na.rm = T
)

min(per.overlap$overlap,
  na.rm = T
)

max(per.overlap$overlap,
  na.rm = T
)
```


```{r}
# Create figure 1c
fig.1c <-
  ggplot(
    data = fig1.DF,
    aes(x = value)
  ) +

  # facet wrap
  facet_wrap(~name,
    scales = "free",
    strip.position = "bottom"
  ) +

  # plot all countries
  geom_density(
    alpha = .5,
    color = "grey70"
  ) +

  # plot sampled countries
  geom_density(
    data = fig1.DF %>%
      filter(sample == "yes"),
    alpha = .5,
    color = "#3C5488"
  ) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank(),
    strip.placement = "outside",
    strip.background = element_blank()
  )
```

# Combine
```{r}
bc <-
  plot_grid(fig.1b,
    fig.1c,
    ncol = 2,
    labels = c("B", "C")
  )

plot_grid(fig.1a,
  bc,
  nrow = 2,
  labels = c("A", "")
)
```


