---
title: "Figure 3: Cross-cultural Analyses"
author: "Nicholas A. Coles, Annabel V. Dang"
description: "Conduct cross-cultural analyses, generating Figure 3 for the manuscript"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r lib}
# Load packages
source("setup.R")
```

#Prep data 
```{r}
# Open data
df <-
  read.csv(file = here(
    "data/output",
    "unique_country_effect_sizes.csv"
  )) %>%
  select(country:ss_var)

# List of effect size columns and variance columns
effect_size_columns <- c(
  "pa_effect_size", "na_effect_size",
  "optimistic_effect_size", "ls_effect_size",
  "envy_effect_size", "indebted_effect_size"
)

variance_columns <- c(
  "pa_var", "na_var", "optimistic_var",
  "ls_var", "envy_var", "indebted_var"
)

# Use lapply to fit models
m.ic <- lapply(1:length(effect_size_columns), function(i) {
  rma.mv(
    yi = df[[effect_size_columns[i]]],
    V = df[[variance_columns[i]]],
    random = list(~ 1 | intervention_condition, ~ 1 | country),
    data = df
  )
})

# Store the results
names(m.ic) <- paste(effect_size_columns)
```

# Pnorm
```{r}
# Compute probability > 0
effect_prob <- function(effect_name, reverse = FALSE) {
  mean_val <- m.ic[[effect_name]][["b"]]
  sd_val <- sqrt(m.ic[[effect_name]][["sigma2"]][[2]])
  prob <- pnorm(q = 0, mean = mean_val, sd = sd_val) * 100
  if (reverse) prob else 100 - prob
}

# Create the table
distribution_results <- data.frame(
  outcome = c("PA", "NA", "Optimism", "Life Satisfaction", "Envy", "Indebtedness"),
  distribution = c(
    effect_prob("pa_effect_size"),
    effect_prob("na_effect_size", reverse = TRUE),
    effect_prob("optimistic_effect_size"),
    effect_prob("ls_effect_size"),
    effect_prob("envy_effect_size", reverse = TRUE),
    effect_prob("indebted_effect_size")
  ),
  opposite_distribution = c(
    effect_prob("pa_effect_size", reverse = TRUE),
    effect_prob("na_effect_size"),
    effect_prob("optimistic_effect_size", reverse = TRUE),
    effect_prob("ls_effect_size", reverse = TRUE),
    effect_prob("envy_effect_size"),
    effect_prob("indebted_effect_size", reverse = TRUE)
  )
)
```

# Calculate effect sizes
```{r}
# Calculate country-level descriptives
d.c <- lapply(effect_size_columns, function(effect_size) {
  d.c <- df %>%
    group_by(country) %>%
    summarise(m = mean(.data[[effect_size]]), .groups = "drop") %>%
    # add [jittered] y-value
    mutate(
      y = 0,
      y = jitter(y, .1)
    ) %>%
    # labels most extreme observations
    mutate(
      label = if_else(m == min(m),
        true = country,
        false = ""
      ),
      label = if_else(m == max(m),
        true = country,
        false = label
      )
    ) %>%
    # include effect size name
    mutate(effect_size = effect_size)

  return(d.c)
})

d.c <- bind_rows(d.c)
d.c <- d.c %>% select(-y, -label)

# Organize effect sizes
mutate_country_results <- d.c %>%
  mutate(
    is_negative = case_when(
      effect_size == "na_effect_size" ~ m > 0,
      effect_size == "envy_effect_size" ~ m > 0,
      TRUE ~ m < 0
    )
  )

country_results <- mutate_country_results %>%
  group_by(effect_size) %>%
  summarise(
    opposite_countries_count = sum(is_negative, na.rm = TRUE),
    opposite_countries_prop = opposite_countries_count / 34,
    countries = str_c(country[is_negative], collapse = "\n"),
    .groups = "drop"
  ) %>%
  rename(outcome = effect_size) %>%
  mutate(
    outcome = recode(
      outcome,
      "pa_effect_size"         = "PA",
      "na_effect_size"         = "NA",
      "optimistic_effect_size" = "Optimism",
      "ls_effect_size"         = "Life Satisfaction",
      "envy_effect_size"       = "Envy",
      "indebted_effect_size"   = "Indebtedness"
    )
  )

print(country_results)
```

# Load and plot data
```{r}
# Join data
universality_data <- left_join(distribution_results, country_results, by = "outcome")

viz.DF <-
  universality_data %>%
  # clean factors
  mutate(
    outcome = factor(outcome,
      levels = c(
        "PA",
        "Optimism",
        "NA",
        "Indebtedness",
        "Life Satisfaction",
        "Envy"
      ),
      labels = c(
        "Positive Affect",
        "Optimism",
        "Negative Affect",
        "Indebtedness",
        "Life Satisfaction",
        "Envy"
      )
    ),
    countries = str_replace_all(
      countries,
      "\n",
      ", "
    )
  )
```

```{r eval = F}
# Write CSV
write.csv(viz.DF,
  file = here(
    "data/output",
    "cultural_consistency.csv"
  )
)

viz.DF <-
  read.csv(file = here(
    "data/output",
    "cultural_consistency.csv")
    )
```

# New Figure 3A
```{r}
i.DF <-
  read.csv(file = here(
    "data",
    "output",
    "intervention_effectsizes.csv")
    ) %>% 
  mutate(se = sqrt(overall.var),
         ci_lower = overall.effect - 1.96 * se,
         ci_upper = overall.effect + 1.96 * se) %>% 
  arrange(overall.effect)

i.DF <-
  i.DF %>% 
  mutate(intervention_condition = 
           factor(intervention_condition,
<<<<<<< Updated upstream
                  levels = c("text", "letter", "naikan", "mental.sub", "divine.grat", "list"),
                  labels = c('Gratitude Text',
                             'Gratitude Letter',
                             'Naikan Reflection',
                             'Mental Subtraction',
                             'Divine Gratitude',
                             'Gratitude List')
=======
                  levels =
                    i.DF$intervention_condition,
                  labels = c('Gratitude List',
                             'Mental Subtraction',
                             'Divine Gratitute',
                             'Naikan Reflection',
                             'Gratitude Letter',
                             'Gratitude Text')
>>>>>>> Stashed changes
                  )
         )
```

```{r}
<<<<<<< Updated upstream
fig.3a <- ggplot(data = i.DF,
=======
fig3c <-
  ggplot(data = i.DF,
>>>>>>> Stashed changes
       aes(x = overall.effect,
           y = intervention_condition)) +
  geom_segment(
    aes(x = ci_lower,
        xend = ci_upper,
        color = '#E64B35')
    ) +
  geom_point(shape = 18,
             size = 4,
             color = '#E64B35') +
  
  xlim(c(0, .6)) +
  xlab(expression(
    paste("Overall efficacy (Cohen's ", 
          italic("d"), 
          ")"
          )
    )) +
  ylab('Practice') +
  theme_classic() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0,
             color = "gray30", 
             linetype = "dotted")
```


#Plot fig 3b
```{r}
# Plot figure 3a
fig.3b <-
  ggplot(
    data = viz.DF,
    aes(
      y = outcome,
      x = opposite_distribution,
      label = countries
    )
  ) +
  geom_col(
    alpha = .5,
    fill = "gray30"
  ) +
  geom_text(aes(x = 18),
    size = 3,
    hjust = 0,
    color = "#3C5488"
  ) +
<<<<<<< Updated upstream
  theme_classic() +
  xlim(0, 100) +
  xlab("Theory-Inconsistent Proportion of Estimated Distribution") +
=======
  # # vertical line
  # geom_segment(x = 90, xend = 90, y = 0.75, yend = 5.25, color = "#3C5488") +
  # # top horizontal
  # geom_segment(x = 89, xend = 90, y = 5.25, yend = 5.25, color = "#3C5488") +
  # # bottom horizontal
  # geom_segment(x = 89, xend = 90, y = 0.75, yend = 0.75, color = "#3C5488") +
  # 
  # geom_text(
  #   aes(
  #     x = 53,
  #     y = length(unique(outcome)) / 1.9
  #   ),
  #   label = "Theory-inconsistent observations",
  #   hjust = 0,
  #   size = 3,
  #   color = "#3C5488"
  # ) +
  theme_classic() +
  xlim(0, 100) +
  xlab("Theory-inconsistent proportion of estimated effect size distribution") +
>>>>>>> Stashed changes
  ylab("Outcome")

fig.3b

```

# Prep data for fig.3c
```{r}
country.DF <-
  # open data
  read.csv(here(
    "data/output",
    "unique_country_effect_sizes.csv"
  )) %>%
  # summarise
  group_by(country) %>%
  summarise(across(everything(), mean, na.rm = TRUE))

mod.DF <-
  read.csv(here(
    "data/final-data",
    "crossculturalmod.csv"
  )) %>%
  filter(sample == "yes")
```

# Join dataframes
```{r}
# Join
DF <-
  left_join(
    x = country.DF,
    y = mod.DF,
    by = "country"
  )

# Delete vestigial
rm(
  country.DF,
  mod.DF
)
```

# Bayesian Correlation Analyses
```{r}
# Created expanded list of outcome-moderator combinations
out.list <-
  c(
    "pa_effect_size",
    "na_effect_size",
    "optimistic_effect_size",
    "ls_effect_size",
    "envy_effect_size",
    "indebted_effect_size"
  )

mod.list <-
  c(
    "relational_mobility",
    "responsibilism",
    "tightness",
    "relig_mean",
    "mean_GDP",
    "resmobility",
    "power.distance",
    "individualism",
    "motivation",
    "uncertainty.avoidance",
    "long.term.orientation",
    "indulgence"
  )

expanded.list <-
  expand_grid(
    out.list,
    mod.list
  )

results <- sapply(
  X = seq_len(nrow(expanded.list)),
  simplify = FALSE,
  FUN = function(i) {
    df <- DF %>%
      select(
        expanded.list$out.list[i],
        expanded.list$mod.list[i]
      )

    names(df) <- c("x", "y")

    # Pearson correlation
    cor.est <- cor(
      x = df$x,
      y = df$y,
      use = "pairwise.complete.obs",
      method = "pearson"
    )

    # Bayes factor
    bf.est <- correlationBF(
      x = df$x,
      y = df$y
    )

    # correlation test (gives CI + p)
    cor.test.res <- cor.test(
      df$x, df$y,
      method = "pearson",
      use = "pairwise.complete.obs"
    )

    data.frame(
      outcome = expanded.list$out.list[i],
      moderator = expanded.list$mod.list[i],
      cor.est = cor.est,
      bf = extractBF(bf.est)$bf,
      ci.lower = cor.test.res$conf.int[1],
      ci.upper = cor.test.res$conf.int[2]
    )
  }
)

# Combine list
results <-
  do.call(rbind, results) %>%
  as.data.frame() %>%
  mutate(
    cor.est = as.numeric(cor.est),
    cor.est = round(cor.est, 2),
    bf = as.numeric(bf),
    logbf = log(bf),
    logbf = round(logbf, 2),
    ci.lower = round(as.numeric(ci.lower), 2),
    ci.upper = round(as.numeric(ci.upper), 2)
  ) %>%
  # clean aesthetics
  mutate(outcome = factor(outcome,
    levels = c(
      "pa_effect_size",
      "na_effect_size",
      "optimistic_effect_size",
      "ls_effect_size",
      "envy_effect_size",
      "indebted_effect_size"
    ),
    labels = c(
      "Positive Affect",
      "Negative Affect",
      "Optimism",
      "Life Satisfaction",
      "Envy",
      "Indebtedness"
    )
  )) %>%
  mutate(moderator = factor(moderator,
    levels = c(
      "individualism",
      "tightness",
      "relational_mobility",
      "resmobility",
      "responsibilism",
      "relig_mean",
      "mean_GDP",
      "power.distance",
      "motivation",
      "uncertainty.avoidance",
      "long.term.orientation",
      "indulgence"
    ),
    labels = c(
      "Individualism",
      "Tightness",
      "Relational Mobility",
      "Residential Mobility",
      "Responsibilism",
      "Religiosity",
      "GDP",
      "Power Distance",
      "Motivation",
      "Uncertainty Avoidance",
      "Long Term Orientation",
      "Indulgence"
    )
  ))

# Minor edit to label
results <- results %>%
  mutate(cor.lab = paste0(
    "paste(",
    "italic(r), ' = ",
    cor.est,
    "')"
  ))

# Restructure
results <- results %>%
  mutate(
    outcome = fct_reorder(outcome, -logbf),
    moderator = fct_reorder(moderator, -logbf)
  )

# Recalculate bf scale
results <- results %>%
  mutate(
    bf.type =
      if_else(bf > .9999,
        "BF['1,0']",
        "BF['0,1']"
      ),
    bf.tran =
      if_else(bf > .9999,
        bf,
        1 / bf
      ),
    bf.tran =
      round(
        bf.tran,
        2
      ),
    bf.tran.dir =
      if_else(bf > .9999,
        bf.tran,
        bf.tran * (-1)
      ),
    bf.lab =
      paste0(
        "paste(",
        "italic(",
        bf.type,
        ")",
        ", ' = ",
        bf.tran,
        "')"
      )
  )
```

```{r}
# Write CSV
write.csv(results,
  file = here(
    "data/output",
    "moderators.csv"
  )
)
```

# Create final fig.3c
```{r}
# Create figure 3c
fig.3c <- ggplot(
  data = results,
  aes(
    x = moderator,
    y = fct_rev(outcome),
    fill = cor.est,
    label = bf.lab
  )
) +
  geom_tile(
    aes(fill = cor.est),
<<<<<<< Updated upstream
    color = "white",
=======
>>>>>>> Stashed changes
    width = 0.97, height = 0.97,
    show.legend = TRUE
  ) +

  # Fill gradient now for correlation
  scale_fill_gradient2(
    low = "#d73027", mid = "white", high = "#4575b4",
    midpoint = 0,
    limits = c(-.5, .5), # adjust limits to correlation range
    name = expression("Pearson's " * italic("r"))
  ) +

  # Text labels for Bayes factor
  geom_text(
    aes(label = bf.lab),
    parse = TRUE,
    nudge_y = -0.25,
    size = 3.5
  ) +

  # Text labels for correlation
  geom_text(
    aes(label = cor.lab),
    parse = TRUE,
    nudge_y = 0.25,
    size = 3.5
  ) +
  theme_classic() +
  labs(
    y = expression("Country-Level Effects of Gratitude Interventions (" * italic("d") * ")"),
    x = "Country-Level Differences",
    fill = expression("Pearson's " * italic("r"))
  ) +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_text(size = 10, margin = margin(b = 15)),
    legend.key.size = unit(0.6, "cm")
  )
```

#Combine
```{r}
<<<<<<< Updated upstream

plot_grid(
  plot_grid(
    fig.3a,
    fig.3b,
    labels = c("A", "B"),
    ncol = 2
  ),
  fig.3c,
  labels = c("", "C"),
  ncol = 1,
  rel_heights = c(0.55,1.45)
)
=======
plot_grid(plot_grid(fig3c, 
                    ggdraw(),
                    fig.3a,
                    labels = c("A", "", "B"),
                    nrow = 1,
                    rel_widths = c(.49, .02, .49)),
          ggdraw(),
          plot_grid(fig.3b,
                    labels = c("C")),
          nrow = 3,
          rel_heights = c(.3, .05, .75))
>>>>>>> Stashed changes
```

